
package telas;

import br.com.senac.checkpets.CheckPets;
import jakarta.persistence.EntityManager;
import javax.swing.JOptionPane;                         // para exibir mensagens
import model.Usuario;                                  // sua entidade Usuario
import telas.Login;

/**
 *
 * @FernandoHenry
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {        
        initComponents();        
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCheck = new javax.swing.JLabel();
        lblPets = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pdSenha = new javax.swing.JPasswordField();
        btEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(31, 89, 116));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbCheck.setBackground(new java.awt.Color(0, 0, 0));
        lbCheck.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 90)); // NOI18N
        lbCheck.setForeground(new java.awt.Color(255, 255, 255));
        lbCheck.setText("Check");
        lbCheck.setToolTipText("");

        lblPets.setBackground(new java.awt.Color(0, 0, 0));
        lblPets.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 90)); // NOI18N
        lblPets.setForeground(new java.awt.Color(255, 255, 255));
        lblPets.setText("Pets");

        lblLogin.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");

        lblSenha.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");

        btEntrar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        btEntrar.setForeground(new java.awt.Color(31, 91, 116));
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lbCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPets, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEntrar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblLogin)
                                .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                .addComponent(lblSenha)
                                .addComponent(pdSenha)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCheck)
                        .addGap(72, 72, 72))
                    .addComponent(lblPets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha)
                .addGap(18, 18, 18)
                .addComponent(pdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btEntrar)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        
        EntityManager em = CheckPets.getEntityManager();
        
        String loginDigitado = txtLogin.getText();
        String passwordDigitado = new String (pdSenha.getPassword());
        
        try{
            
            Usuario usuario = em.createQuery(
            "SELECT u FROM Usuario u WHERE u.login =:login AND u.senha = :senha", Usuario.class
            )
                    .setParameter("login", loginDigitado)
                    .setParameter("senha", passwordDigitado)
                    .getSingleResult();            
        
        JOptionPane.showMessageDialog( // exibe um diálogo informando sucesso no login
                    this, "Olá, " + usuario.getFuncionario().getNome()+ "!\n"
                            + "Seja bem vindo ao CheckPets!");
                       
        TelaInicial telaInicial = new TelaInicial(usuario);
        telaInicial.setVisible(true);
        this.dispose();                
        }
        
         catch (jakarta.persistence.NoResultException ex) {           // captura quando a consulta não encontra nenhum usuário

            JOptionPane.showMessageDialog( // informa que as credenciais são inválidas
                    this,
                    "Usuário ou senha inválidos!",
                    "Falha no login",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {                                     // captura outras exceções (conexão, provider, etc.)

            JOptionPane.showMessageDialog( // exibe mensagem genérica com o detalhe do erro
                    this,
                    "Erro ao tentar logar: " + ex.getMessage(),
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } finally {                                                  // bloco que sempre executa, com sucesso ou erro

            if (em != null && em.isOpen()) {                         // se o EntityManager foi criado e ainda está aberto
                em.close();                                          // fecha o EntityManager para liberar recursos
            }
        }                                                            // fim do try/catch/finally
        // fim do método
        
        
              
            
        

    }//GEN-LAST:event_btEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCheck;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPets;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pdSenha;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
