package telas;

import model.Funcionario;
import model.Usuario;

/**
 *
 * @author Fernando Henry
 */
public class TelaInicial extends javax.swing.JFrame {

    private Usuario usuarioLogado;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();
        definirPermissoes();
    }

    public void definirPermissoes() {
        Funcionario funcionario = usuarioLogado.getFuncionario();

        int permissao = funcionario.getMatricula();

        switch (permissao) {
            case 1: //Gerente
                btCadastrarFuncionario.setEnabled(true);
                btCadastrarPet.setEnabled(false);
                btListagem.setEnabled(true);
                btSair.setEnabled(true);
                btRealizarConsulta.setEnabled(false);
                break;

            case 2: //Atendente
                btCadastrarFuncionario.setEnabled(false);
                btCadastrarPet.setEnabled(true);
                btListagem.setEnabled(true);
                btSair.setEnabled(true);
                btRealizarConsulta.setEnabled(false);
                break;

            case 4: //Veterinário 1
                btCadastrarFuncionario.setEnabled(false);
                btCadastrarPet.setEnabled(false);
                btListagem.setEnabled(true);
                btSair.setEnabled(true);
                btRealizarConsulta.setEnabled(true);
                break;

            case 5://Veternário 2
                btCadastrarFuncionario.setEnabled(false);
                btCadastrarPet.setEnabled(false);
                btListagem.setEnabled(true);
                btSair.setEnabled(true);
                btRealizarConsulta.setEnabled(true);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCheck = new javax.swing.JLabel();
        lblPets = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        btCadastrarFuncionario = new javax.swing.JButton();
        btCadastrarPet = new javax.swing.JButton();
        btRealizarConsulta = new javax.swing.JButton();
        btListagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bem-vindo(a)!");

        jPanel1.setBackground(new java.awt.Color(31, 89, 116));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbCheck.setBackground(new java.awt.Color(0, 0, 0));
        lbCheck.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 90)); // NOI18N
        lbCheck.setForeground(new java.awt.Color(255, 255, 255));
        lbCheck.setText("Check");
        lbCheck.setToolTipText("");

        lblPets.setBackground(new java.awt.Color(0, 0, 0));
        lblPets.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 90)); // NOI18N
        lblPets.setForeground(new java.awt.Color(255, 255, 255));
        lblPets.setText("Pets");

        btSair.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        btSair.setForeground(new java.awt.Color(31, 89, 116));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btCadastrarFuncionario.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        btCadastrarFuncionario.setForeground(new java.awt.Color(31, 89, 116));
        btCadastrarFuncionario.setText("Cadastrar Funcionario");
        btCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarFuncionarioActionPerformed(evt);
            }
        });

        btCadastrarPet.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        btCadastrarPet.setForeground(new java.awt.Color(31, 89, 116));
        btCadastrarPet.setText("Cadastrar Pet");
        btCadastrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarPetActionPerformed(evt);
            }
        });

        btRealizarConsulta.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        btRealizarConsulta.setForeground(new java.awt.Color(31, 89, 116));
        btRealizarConsulta.setText("Realizar Consulta");
        btRealizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarConsultaActionPerformed(evt);
            }
        });

        btListagem.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        btListagem.setForeground(new java.awt.Color(31, 89, 116));
        btListagem.setText("Listagem");
        btListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(lbCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPets, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btCadastrarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btRealizarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btCadastrarPet)
                                    .addComponent(btListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 83, Short.MAX_VALUE)
                        .addComponent(lblPets, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarPet, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRealizarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        Login telaLogin = new Login();
        telaLogin.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarFuncionarioActionPerformed
        CadastroFuncionario cadastrarFuncionario = new CadastroFuncionario();
        cadastrarFuncionario.setVisible(true);
    }//GEN-LAST:event_btCadastrarFuncionarioActionPerformed

    private void btCadastrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarPetActionPerformed
        CadastroPets cadastrarPets = new CadastroPets();
        cadastrarPets.setVisible(true);
    }//GEN-LAST:event_btCadastrarPetActionPerformed

    private void btRealizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarConsultaActionPerformed
        TelaConsulta consulta = new TelaConsulta();
        consulta.setVisible(true);
    }//GEN-LAST:event_btRealizarConsultaActionPerformed

    private void btListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListagemActionPerformed
       Listagem listagem = new Listagem();
       listagem.setVisible(true);
    }//GEN-LAST:event_btListagemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarFuncionario;
    private javax.swing.JButton btCadastrarPet;
    private javax.swing.JButton btListagem;
    private javax.swing.JButton btRealizarConsulta;
    private javax.swing.JButton btSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCheck;
    private javax.swing.JLabel lblPets;
    // End of variables declaration//GEN-END:variables
}
